name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Restore
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.email "taras.parfeniuk@gmail.com"
          git config --global user.name "taras.parfeniuk"
          npm run deploy-gh-pages