name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Restore and Build
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: gh-pages -d build